name: CMake

on:
  push:
    branches:
      - test

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python 3 with dev dependencies
      shell: bash
      run: sudo apt install python3 python3-dev
    
    - name: Load submodules
      shell: bash
      run: git submodule init; git submodule update
      
    - name: Create Build Environment
      # Create directory for building
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Run the next command at a bash shell
      shell: bash
      # Using the next working directory
      working-directory: ${{runner.workspace}}/build
      # Run cmake
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Run make (in few words)
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Run the resulting test file
      run: ${{runner.workspace}}/build/test
